id = "html-css-js-snippets"
name = "HTML CSS JS Snippets"
version = "0.0.1"
schema_version = 1
authors = ["hongducdev <contact.hongduc@gmail.com>"]
description = "HTML CSS JS snippets for Zed IDE. A collection of HTML, CSS and JS snippets to improve your development speed."
repository = "https://github.com/hongducdev/zed-html-css-js-snippets"
snippets = "./snippets/global.json"